# Generated by Django 4.1.1 on 2023-02-10 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscriptorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('n_projects', models.IntegerField()),
                ('ref_stages', models.IntegerField()),
                ('n_cells', models.IntegerField()),
                ('n_layers', models.IntegerField()),
                ('n_periods', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuscriptionRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('payment', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.suscriptortype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=50)),
                ('modelDescription', models.TextField(default='')),
                ('timeUnitName', models.CharField(choices=[('Undefined', 'Undefined'), ('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Daysw', 'Daysw'), ('Years', 'Years')], default='Seconds', max_length=50)),
                ('lengthUnitName', models.CharField(choices=[('Undefined', 'Undefined'), ('Feet', 'Feet'), ('Meters', 'Meters'), ('Centimeters', 'Centimeters')], default='Meters', max_length=50)),
                ('timeUnitCode', models.IntegerField(default=1)),
                ('lengthUnitCode', models.IntegerField(default=2)),
                ('epsgCode', models.IntegerField(default=32718)),
                ('startDate', models.DateTimeField(default=datetime.date(1970, 1, 1))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.SlugField(max_length=10, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
