"""
Django settings for cloudtest project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# from unipath import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))
# BASE_DIR = Path(__file__).parent.parent
# print(BASE_DIR)

CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v%g%2sp8si=tyepa^kk1@i@4!x5mev@@e#=h=#r@gq+w6@vb)$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Assets Management
ASSETS_ROOT = os.getenv('ASSETS_ROOT', '/static/assets')

ALLOWED_HOSTS = ['tupaccloud.hatarilabs.com',
                 'debiancluster.ddns.net', 'tupacdev.hatarilabs.com', 'localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.gis",
    "mf6.home",
    "bootstrap5",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.keycloak",
     "django_bootstrap_icons",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #"core.middleware.KeycloakIDTokenMiddleware",
]

ROOT_URLCONF = "core.urls"
LOGIN_REDIRECT_URL = "home"  # Route defined in home/urls.py
#LOGOUT_REDIRECT_URL = "https://accounts.hatarilabs.com/realms/demo/protocol/openid-connect/logout"#home"  # Route defined in home/urls.py

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(CORE_DIR, 'mf6/templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "mf6.context_processors.cfg_assets_root"
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = { 
    'tests': {
        'NAME': 'tests.db',
        'ENGINE': 'django.db.backends.sqlite3'
    },
}

default_database = os.environ.get('DJANGO_DATABASE', 'tests')
DATABASES['default'] = DATABASES[default_database]
# To run
# export DJANGO_DATABASE='tests'
# python manage.py runserver 0.0.0.0:7777

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


#############################################################
# SRC: https://devcenter.heroku.com/articles/django-assets

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(CORE_DIR, 'static')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'mf6/static'),
)

##########################################

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

##########################################

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# GDAL_LIBRARY_PATH = r'C:/Users/encue/anaconda3/envs/tupac/Library/bin/gdal304.dll'

MEDIA_URL = '/projects/'
MEDIA_ROOT = '/mnt/tupacProjects'  # review this

# DEFAULT_FILE_STORAGE = 'storages.backends.overwrite.OverwriteStorage'


# Allauth Configuration

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

SITE_ID = 0# this changed from 1 to 0

SOCIALACCOUNT_PROVIDERS = {
    'keycloak': {
        'KEYCLOAK_URL': 'https://accounts.hatarilabs.com',
        'KEYCLOAK_REALM': 'demo',
        'KEYCLOAK_CLIENT_ID': 'djangoTupacCloud',
        'KEYCLOAK_CLIENT_SECRET': 'xrmqy5y9fESkt4xYNZpmB140m4IHHxLq',
        'KEYCLOAK_LOGOUT_URL': 'https://accounts.hatarilabs.com/realms/demo/protocol/openid-connect/logout',
        'POST_LOGOUT_REDIRECT_URI': 'https://tupaccloud.hatarilabs.com',
        'SCOPE': ['openid', 'profile', 'email'],
    },
}

#SOCIALACCOUNT_ADAPTER = 'core.adapter.CustomSocialAccountAdapter'
SOCIALACCOUNT_STORE_TOKENS = True

# ACCOUNT_ADAPTER = 'client.account_adapter.NoNewUsersAccountAdapter'

LOGIN_URL = "mf6-home"
LOGIN_REDIRECT_URL = "mf6-home"
LOGOUT_REDIRECT_URL = "https://accounts.hatarilabs.com/realms/demo/protocol/openid-connect/logout"
ACCOUNT_EMAIL_VERIFICATION = "none"


# PATH_FROM_PROJECTS = config('PATH_FROM_PROJECTS')
CSRF_TRUSTED_ORIGINS = [
    'https://tupaccloud.hatarilabs.com', 'https://tupacdev.hatarilabs.com']
